#!/usr/bin/env python3
"""Regenerate docs/ENV_INVENTORY.md from the `env::var` call sites.

WHY THIS IS GENERATED, NOT HAND-WRITTEN. A hand-maintained list drifts the moment
someone adds a flag, and this repo has well over two hundred. Grepping for the NAME is also
wrong — 28 `ARF_*` strings in the tree are prose in comments, not flags, and an
earlier count of "280" included them. Only an `env::var`/`var_os` call means the
code reads it.

Run: python3 scripts/gen_env_inventory.py
"""
import os, re, subprocess, sys, collections, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
# `env_once!` / `env_once_os!` (island.rs, M1) are process-cached env::var / var_os reads.
PAT = re.compile(r'(?:env::var(?:_os)?|env_once(?:_os)?!)\(\s*"(ARF_[A-Z0-9_]+)"')
# weights.rs reads the shipped kernel levers through `lever_on("ARF_X", default)`, which
# also reads the `ARF_NO_X` hatch by a name it builds at runtime. Neither shows up as a
# literal `env::var("...")`, so count both here.
LEVER = re.compile(r'lever_on\(\s*"(ARF_[A-Z0-9_]+)"')


# `ARF_INDEX_EXCLUDE`, when set, names a file (relative to the repository root, or absolute) that
# lists paths to leave out of the generated inventory: one per line, `#` comments allowed, a trailing
# `/` covers a directory. Unset, nothing is skipped. Set to a file that does not exist, this fails
# rather than silently skipping nothing.
def _load_excluded(root):
    name = os.environ.get("ARF_INDEX_EXCLUDE")
    if not name:
        return []
    f = root / name
    if not f.is_file():
        sys.exit(f"ARF_INDEX_EXCLUDE={name}: no such file under {root}")
    return [l.strip() for l in f.read_text().split("\n") if l.strip() and not l.startswith("#")]


def excluded(rel):
    return any(rel == p or (p.endswith("/") and rel.startswith(p)) for p in EXCLUDED)


EXCLUDED = _load_excluded(ROOT)

def bucket(name: str) -> str:
    if re.search(r"DEBUG|DUMP|PROBE|TRACE|CAPTURE|STAT|PROF|HIST|BISECT|SELFTEST|SHAPE|VERBOSE", name):
        return "Instrumentation"
    if re.match(r"ARF_(NO|SKIP|FORCE|DISABLE)_", name):
        return "Escape hatch"
    return "Configuration"

def main() -> None:
    files = subprocess.run(["find", "crates", "-name", "*.rs"],
                           cwd=ROOT, capture_output=True, text=True).stdout.split()
    files = [f for f in files if not excluded(f)]
    sites = collections.defaultdict(set)
    for f in files:
        for i, line in enumerate((ROOT / f).read_text(errors="ignore").split("\n"), 1):
            for m in PAT.finditer(line):
                # File, NOT file:line. A line number makes this file churn on every
                # `cargo fmt` — the L286 pass shifted all 244 of them and the staleness
                # check fired on a diff that meant nothing.
                sites[m.group(1)].add(f.replace("crates/", ""))
            for m in LEVER.finditer(line):
                name = m.group(1)
                sites[name].add(f.replace("crates/", ""))
                sites["ARF_NO_" + name[len("ARF_"):]].add(f.replace("crates/", ""))

    tot = collections.Counter(bucket(n) for n in sites)
    # The contract's size is read from ENV_SUPPORTED.md (distinct backticked names in the first
    # cell of each table row — `NO_COLOR`, `TERM` share one row) so it cannot drift from that file.
    supported = set()
    for line in (ROOT / "docs/ENV_SUPPORTED.md").read_text().split("\n"):
        if line.startswith("| `"):
            supported.update(re.findall(r"`([A-Z][A-Z0-9_]*)`", line.split("|")[1]))
    out = [
        "# Environment variables — generated inventory", "",
        "> Generated by `scripts/gen_env_inventory.py` from `env::var` call sites. Every entry below is a",
        "> flag the code **actually reads**; names that appear only in comments are excluded.", "",
        "**Three tiers.** *Configuration* changes behaviour and is the candidate public surface.",
        "*Instrumentation* prints or dumps and should never be needed in production.",
        "*Escape hatches* (`NO_`/`SKIP_`/`FORCE_`) disable a default — they exist so a regression has a",
        "one-line workaround, and they are deliberately kept.", "",
        "⚠️ **This file is the inventory, not the contract.** A flag being listed does not make it",
        f"supported \u2014 see [ENV_SUPPORTED.md](ENV_SUPPORTED.md) for the {len(supported)} that are.", "",
        "| tier | count |", "|---|---|",
    ]
    for k in ("Configuration", "Instrumentation", "Escape hatch"):
        out.append(f"| {k} | {tot[k]} |")
    out += ["", f"**{sum(tot.values())} flags read from the environment.**", ""]
    for tier in ("Configuration", "Instrumentation", "Escape hatch"):
        out += [f"## {tier}", "", "| flag | read at |", "|---|---|"]
        for n in sorted(x for x in sites if bucket(x) == tier):
            locs = sorted(sites[n])
            where = f"`{locs[0]}`" + (f" +{len(locs)-1} more" if len(locs) > 1 else "")
            out.append(f"| `{n}` | {where} |")
        out.append("")
    (ROOT / "docs/ENV_INVENTORY.md").write_text("\n".join(out))
    print(f"docs/ENV_INVENTORY.md: {sum(tot.values())} flags "
          f"({tot['Configuration']} config, {tot['Instrumentation']} debug, {tot['Escape hatch']} escape)")

if __name__ == "__main__":
    main()
