#!/usr/bin/env python3
"""Regenerate docs/KERNEL_MAP.md — an index of every shader in the tree.

145 shaders sit in one flat directory. That is not bloat (all 145 are referenced by the
loader), but it is unnavigable: the family structure — {operation} x {quantization} x
{batched?} x {backend} — is invisible in a sorted `ls`. This writes it down.

`--check` compares without writing; scripts/check_generated_docs.sh runs that in CI.
"""
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SHADERS = ROOT / "crates/arf-gpu/src/shaders"


def summary(path):
    """The shader's own first comment line, which every one of them has."""
    for line in path.read_text(errors="ignore").splitlines()[:6]:
        line = line.strip()
        if line.startswith("//") and not line.startswith("///"):
            text = line.lstrip("/").strip()
            if text:
                return text
    return ""


def group(name):
    if name.startswith(("matmul_vec_moe", "moe", "gemv_q4ks_id")):
        return "MoE — routed expert GEMV and reduction"
    if name.startswith(("matmul_vec", "mtp_")):
        return "Decode GEMV — one row against the weights (the hot path)"
    if name.startswith("matmul_coop"):
        return "Cooperative-matrix GEMM — simdgroup_matrix tiles (prefill, FLUX)"
    if name.startswith("matmul"):
        return "Dense GEMM"
    if name.startswith(("attention", "attn", "kv_", "flash")):
        return "Attention and KV cache"
    if name.startswith(("gdn", "gated_delta", "ssm")):
        return "Gated delta net / SSM (the recurrent layers)"
    if name.startswith(("rope", "rmsnorm", "layernorm", "qk_norm", "add", "mul", "silu",
                        "swiglu", "geglu", "gelu", "quick_gelu", "group_norm", "softmax",
                        "scale", "copy", "slice", "row_bias", "add_bias", "upsample",
                        "qkv_norm", "v_norm", "softcap", "decode_ops", "gemma_normpair")):
        return "Elementwise, norms and small ops"
    if name.startswith(("embed", "sample", "argmax", "logit", "reduce", "sort", "csr")):
        return "Embedding, sampling and reductions"
    if name.startswith(("vae", "dit", "clip", "t5", "flux", "im2col", "conv", "adaln", "text_attn")):
        return "FLUX — image generation"
    if name.startswith("vision"):
        return "Vision (SigLIP)"
    return "Other"


ORDER = [
    "Decode GEMV — one row against the weights (the hot path)",
    "Cooperative-matrix GEMM — simdgroup_matrix tiles (prefill, FLUX)",
    "Dense GEMM",
    "MoE — routed expert GEMV and reduction",
    "Attention and KV cache",
    "Gated delta net / SSM (the recurrent layers)",
    "Elementwise, norms and small ops",
    "Embedding, sampling and reductions",
    "FLUX — image generation",
    "Vision (SigLIP)",
    "Other",
]


def build():
    rows = []
    # L364b moved the shaders into `metal/` and `wgsl/`; `iterdir()` on the parent then found
    # NOTHING and this generator wrote a map of "0 shaders" without complaint (2026-09-19).
    # Sort by file name, not path, so the order is the one the flat layout had.
    for p in sorted(SHADERS.rglob("*"), key=lambda q: q.name):
        if p.suffix not in (".wgsl", ".metal"):
            continue
        rows.append((p.stem, p.suffix.lstrip("."), summary(p)))

    if not rows:
        sys.exit(f"gen_kernel_map: found no shaders under {SHADERS} — refusing to write an empty map")

    out = [
        "# Kernel map",
        "",
        "<!-- Generated by scripts/gen_kernel_map.py. Do not edit by hand. -->",
        "",
        f"{len(rows)} shaders, every one referenced by the loader. They live in two",
        "directories, `shaders/metal/` and `shaders/wgsl/`, split only by language; this file",
        "is the structure those directories do not show.",
        "",
        "**Reading the names.** Most are a point in a matrix:",
        "`matmul_vec` (GEMV) or `matmul_coop` (tiled GEMM), then the quantization (`q4`, `q4k`,",
        "`q4ks`, `q3k`, `q8`), then `_batch` for the B-row form, then `_msl` for the native-Metal",
        "twin of a WGSL kernel. `_b` marks a B-parallel variant, `_sg` a subgroup reduction.",
        "",
        "The `.metal` files are the native-Metal island — the path every shipped token takes on",
        "macOS. The `.wgsl` files are the portable wgpu path, and are what FLUX and the",
        "prefill GEMMs use. See [KERNELS.md](KERNELS.md) for what each one costs.",
        "",
    ]
    for g in ORDER:
        items = [r for r in rows if group(r[0]) == g]
        if not items:
            continue
        out += [f"## {g}", "", "| shader | backend | what it does |", "|---|---|---|"]
        for stem, ext, doc in sorted(items):
            doc = doc.replace("|", "\\|")
            if len(doc) > 104:
                doc = doc[:101].rstrip() + "…"
            out.append(f"| `{stem}` | {ext} | {doc} |")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def main():
    body = build()
    target = ROOT / "docs/KERNEL_MAP.md"
    if "--check" in sys.argv:
        if not target.exists() or target.read_text() != body:
            print("docs/KERNEL_MAP.md is stale — run: python3 scripts/gen_kernel_map.py")
            return 1
        return 0
    target.write_text(body)
    print(f"docs/KERNEL_MAP.md: {body.count('| `')} shaders indexed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
